// EasyFreezy native gray layer (dart:ffi, C-ABI).
//
//   crypt — shared XOR keystream (port of lib/sleet/mixer.dart)
//   table — GENERATED by tool/sleet/gen_rust.dart: the encrypted string table
//           (sleet_reveal/sleet_free) plus the encrypted SLOT_PARAMS blob
//   slot  — native slot math: strips, RNG, spin evaluation, payouts
//
// The exported C functions live in the submodules; #[no_mangle] keeps them
// visible from the cdylib regardless of module nesting.
#![allow(clippy::all)]

mod crypt;
mod slot;
mod table;
