// Gray-layer string provider.
//
// All sensitive strings (relay endpoint + secret, AppsFlyer/GCD, push project,
// the full user-agent vocabulary, the WebView JS injections and the relay
// screen copy) live encrypted inside the native Rust component (`libsleet.so`)
// and are revealed one call at a time over dart:ffi. Nothing here holds the
// plaintext; see `rust/src/lib.rs` (generated by `tool/sleet/gen_rust.dart`).
import 'dart:convert';
import 'dart:ffi';

typedef _RevealNative = Pointer<Uint8> Function(Int32);
typedef _RevealDart = Pointer<Uint8> Function(int);
typedef _FreeNative = Void Function(Pointer<Uint8>);
typedef _FreeDart = void Function(Pointer<Uint8>);

// FFI ids — must stay in sync with the DATA order in rust/src/lib.rs.
const int _idEndpoint = 0;
const int _idRelaySecret = 1;
const int _idGcd = 2;
const int _idFlyerKey = 3;
const int _idPushProject = 4;
const int _idProduct = 5;
const int _idLinuxOpen = 6;
const int _idBuildLabel = 7;
const int _idBuildClose = 8;
const int _idEngineLabel = 9;
const int _idEngineTail = 10;
const int _idChromeLabel = 11;
const int _idSafariLabel = 12;
const int _idChrome = 13;
const int _idWebkit = 14;
const int _idSafeArea = 15;
const int _idKeyboard = 16;
const int _idAutoplay = 17;
const int _idHook = 18;
const int _idInviteTitle = 19;
const int _idInviteBody = 20;
const int _idGapTitle = 21;
const int _idGapBody = 22;

const int _count = 23;

class _Sleet {
  _Sleet._(this._reveal, this._free);

  final _RevealDart _reveal;
  final _FreeDart _free;

  static bool _tried = false;
  static _Sleet? _it;

  static _Sleet? get it {
    if (_tried) return _it;
    _tried = true;
    try {
      final lib = DynamicLibrary.open('libsleet.so');
      _it = _Sleet._(
        lib.lookupFunction<_RevealNative, _RevealDart>('sleet_reveal'),
        lib.lookupFunction<_FreeNative, _FreeDart>('sleet_free'),
      );
    } catch (_) {
      _it = null;
    }
    return _it;
  }

  String reveal(int id) {
    final ptr = _reveal(id);
    if (ptr == nullptr) return '';
    try {
      var len = 0;
      while (ptr[len] != 0) {
        len++;
      }
      if (len == 0) return '';
      return utf8.decode(ptr.asTypedList(len));
    } finally {
      _free(ptr);
    }
  }
}

final List<String?> _cache = List<String?>.filled(_count, null);

String _open(int id) {
  final hit = _cache[id];
  if (hit != null) return hit;
  final value = _Sleet.it?.reveal(id) ?? '';
  _cache[id] = value;
  return value;
}

String openEndpoint() => _open(_idEndpoint);
String openRelaySecret() => _open(_idRelaySecret);
String openGcdBase() => _open(_idGcd);
String openFlyerKey() => _open(_idFlyerKey);
String openPushProject() => _open(_idPushProject);
String openProduct() => _open(_idProduct);
String openLinuxOpen() => _open(_idLinuxOpen);
String openBuildLabel() => _open(_idBuildLabel);
String openBuildClose() => _open(_idBuildClose);
String openEngineLabel() => _open(_idEngineLabel);
String openEngineTail() => _open(_idEngineTail);
String openChromeLabel() => _open(_idChromeLabel);
String openSafariLabel() => _open(_idSafariLabel);
String openChrome() => _open(_idChrome);
String openWebkit() => _open(_idWebkit);
String openSafeArea() => _open(_idSafeArea);
String openKeyboard() => _open(_idKeyboard);
String openAutoplay() => _open(_idAutoplay);
String openHook() => _open(_idHook);

String openInviteTitle() => _open(_idInviteTitle);
String openInviteBody() => _open(_idInviteBody);
String openGapTitle() => _open(_idGapTitle);
String openGapBody() => _open(_idGapBody);

String openGcdCall(String applicationId, String deviceId) {
  final base = openGcdBase();
  if (base.isEmpty || deviceId.isEmpty) return '';
  return '$base$applicationId?devkey=${openFlyerKey()}&device_id=$deviceId';
}
