// Generates rust/src/table.rs — the encrypted data island for the native gray
// layer: the "gray part" string table (consumed over dart:ffi by
// lib/sleet/veil.dart) plus the encrypted slot-math parameter blob
// (`SLOT_PARAMS`, consumed by rust/src/slot.rs).
//
// Plaintext is the canonical dev-only data in tool/sleet/plain.dart. Byte
// arrays are produced with the exact same keystream as lib/sleet/mixer.dart, so
// the Rust `reveal`/`reveal_bytes` (a straight port of that keystream, in
// rust/src/crypt.rs) decode them identically. The hand-written modules
// (crypt.rs, slot.rs, lib.rs) are never touched by this generator, so it is
// self-contained and safe to re-run at any time.
//
//   dart run tool/sleet/gen_rust.dart
import 'dart:io';

import 'package:easy_freezy/sleet/mixer.dart';

import 'plain.dart' as plain;

/// Ordered table — the index is the FFI id shared with veil.dart.
final List<MapEntry<String, String>> _table = plain.table;

const String _head = r'''// GENERATED by tool/sleet/gen_rust.dart — do not edit by hand.
// Many ID_* constants are consumed only across the FFI boundary (via
// sleet_reveal from Dart), so the Rust compiler cannot see their uses.
#![allow(dead_code)]
use std::ffi::CString;
use std::os::raw::c_char;

use crate::crypt::reveal;

/// Reveals the string-table entry for `id`, returning a freshly allocated C
/// string the caller must release with `sleet_free`. Unknown ids yield "".
#[no_mangle]
pub extern "C" fn sleet_reveal(id: i32) -> *mut c_char {
    let s = if id >= 0 && (id as usize) < DATA.len() {
        reveal(DATA[id as usize])
    } else {
        String::new()
    };
    match CString::new(s) {
        Ok(c) => c.into_raw(),
        Err(_) => CString::new("").unwrap().into_raw(),
    }
}

/// Releases a string previously handed out by `sleet_reveal`.
#[no_mangle]
pub extern "C" fn sleet_free(ptr: *mut c_char) {
    if ptr.is_null() {
        return;
    }
    unsafe {
        let _ = CString::from_raw(ptr);
    }
}

''';

String _wrapStr(List<int> bytes, String name, int id) {
  final buf = StringBuffer('    &[');
  buf.write(bytes.join(', '));
  buf.write('], // $id $name');
  return buf.toString();
}

/// camelCase → SCREAMING_SNAKE_CASE (used for the pub(crate) ID_* constants).
String _constName(String camel) {
  final buf = StringBuffer();
  for (var i = 0; i < camel.length; i++) {
    final c = camel[i];
    if (i > 0 && c.toUpperCase() == c && c.toLowerCase() != c) {
      buf.write('_');
    }
    buf.write(c.toUpperCase());
  }
  return buf.toString();
}

void main() {
  final out = StringBuffer(_head);

  // Encrypted slot-math parameters (weights, paytable, scatter tables, seeds).
  final params = plain.slotParams;
  final foldedParams = foldBytes(params);
  // XOR is an involution: folding the folded bytes must restore the original.
  final roundParams = foldBytes(foldedParams);
  if (roundParams.length != params.length ||
      !List.generate(params.length, (i) => roundParams[i] == params[i])
          .every((ok) => ok)) {
    stderr.writeln('slot params round-trip failed');
    exitCode = 1;
    return;
  }
  out.writeln(
      '/// Encrypted slot-math parameter blob (${params.length} bytes). See');
  out.writeln('/// tool/sleet/plain.dart for the byte layout; decoded in slot.rs.');
  out.writeln('pub(crate) static SLOT_PARAMS: &[u8] = &[');
  out.writeln('    ${foldedParams.join(', ')},');
  out.writeln('];');
  out.writeln();

  // Public (crate-visible) ID constants for every table entry. Rust modules
  // (net.rs etc.) resolve ciphertext via `DATA[ID_*]`.
  out.writeln('// String table ids (shared with lib/sleet/veil.dart for the');
  out.writeln('// Dart-visible subset; the rest are consumed only inside Rust).');
  for (var id = 0; id < _table.length; id++) {
    out.writeln(
        'pub(crate) const ID_${_constName(_table[id].key)}: usize = $id;');
  }
  out.writeln();

  // Encrypted gray-layer string table.
  out.writeln('pub(crate) static DATA: &[&[u8]] = &[');
  for (var id = 0; id < _table.length; id++) {
    final entry = _table[id];
    final bytes = fold(entry.value);
    // Sanity: Rust uses the same keystream, so reveal(fold(x)) must == x.
    if (reveal(bytes) != entry.value) {
      stderr.writeln('round-trip failed for ${entry.key}');
      exitCode = 1;
      return;
    }
    out.writeln(_wrapStr(bytes, entry.key, id));
  }
  out.writeln('];');

  final dir = Directory('rust/src');
  dir.createSync(recursive: true);
  File('rust/src/table.rs').writeAsStringSync(out.toString());
  stdout.writeln(
      'wrote rust/src/table.rs — ${_table.length} strings + ${params.length} slot bytes');
}
